import { useEffect, useRef, useState } from "react";
import { Banner, Button, Details, Icon, Input, MonoBlock } from "@lasso/ui";
import { api, core, presets as presetModels } from "../bindings";
import { looksLikeURL } from "../format";
import { AdvancedDrawer } from "./AdvancedDrawer";
import { MetadataCard, MetadataSkeleton } from "./MetadataCard";
import { PresetBar } from "./PresetBar";
import { QualityPicks } from "./QualityPicks";

const EMPTY_OPTIONS = {
  url: "",
  pick: "best",
  container: "",
  videoCodec: "",
  audioCodec: "",
  subtitles: { download: false, embed: false, languages: [], autoGenerated: false },
  enhancements: { sponsorBlock: "", sponsorBlockCategories: [], embedChapters: false, embedThumbnail: false, embedMetadata: false },
  playlist: { start: 0, end: 0, reverse: false },
  network: { rateLimit: "", cookies: "" },
  output: { folder: "", template: "" },
} as unknown as core.Options;

/**
 * Composer is the left pane: the whole default flow is the field at the top and
 * one row of chips. Everything else is folded away until asked for.
 */
export function Composer({
  presets,
  onPresetsChanged,
  disabled,
}: {
  presets: presetModels.Preset[] | null;
  onPresetsChanged: () => void;
  disabled: boolean;
}) {
  const [url, setUrl] = useState("");
  const [options, setOptions] = useState<core.Options>(EMPTY_OPTIONS);
  const [metadata, setMetadata] = useState<core.Metadata | null>(null);
  const [resolving, setResolving] = useState(false);
  const [error, setError] = useState("");
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [command, setCommand] = useState("");
  const [activePreset, setActivePreset] = useState<string | null>(null);
  const [queued, setQueued] = useState(false);

  const urlRef = useRef<HTMLInputElement>(null);
  // A resolve in flight must not overwrite a newer one that already finished.
  const resolveToken = useRef(0);

  async function resolve(target = url) {
    const trimmed = target.trim();
    if (!trimmed || disabled) return;

    const token = ++resolveToken.current;
    setError("");
    setMetadata(null);
    setResolving(true);
    try {
      const result = await api.FetchMetadata(trimmed);
      if (token === resolveToken.current) setMetadata(result);
    } catch (e) {
      if (token === resolveToken.current) setError(cleanError(e));
    } finally {
      if (token === resolveToken.current) setResolving(false);
    }
  }

  async function download() {
    if (!metadata || disabled) return;
    setError("");
    try {
      await api.Enqueue({ ...options, url: url.trim() } as core.Options, metadata.title);
      // Confirm without clearing: the same link is often downloaded twice at
      // different qualities, and wiping the field would punish that.
      setQueued(true);
      setTimeout(() => setQueued(false), 1800);
    } catch (e) {
      setError(cleanError(e));
    }
  }

  async function showCommand() {
    setError("");
    try {
      setCommand(await api.ShowCommand({ ...options, url: url.trim() } as core.Options));
    } catch (e) {
      setError(cleanError(e));
    }
  }

  // Cmd+V anywhere puts a link in the field and resolves it, so the common case
  // never requires aiming at an input first.
  useEffect(() => {
    function onPaste(event: ClipboardEvent) {
      const target = event.target as HTMLElement | null;
      const typing = target?.tagName === "INPUT" || target?.tagName === "TEXTAREA";
      const text = event.clipboardData?.getData("text") ?? "";
      if (!looksLikeURL(text)) return;

      // Inside the field, let the paste land and then resolve it.
      if (typing && target === urlRef.current) {
        setUrl(text.trim());
        event.preventDefault();
        void resolve(text.trim());
        return;
      }
      if (typing) return;

      event.preventDefault();
      setUrl(text.trim());
      urlRef.current?.focus();
      void resolve(text.trim());
    }

    window.addEventListener("paste", onPaste);
    return () => window.removeEventListener("paste", onPaste);
  });

  const canDownload = Boolean(metadata) && !resolving && !disabled;

  return (
    <section
      className="flex min-h-0 flex-1 flex-col gap-md overflow-y-auto p-md"
      onKeyDown={(e) => {
        if (e.key === "Escape" && drawerOpen) {
          setDrawerOpen(false);
          e.stopPropagation();
        }
      }}
    >
      <Input
        ref={urlRef}
        value={url}
        autoFocus
        spellCheck={false}
        placeholder="Paste a link"
        aria-label="Link to download"
        disabled={disabled}
        onChange={(e) => {
          setUrl(e.target.value);
          setMetadata(null);
          setError("");
        }}
        onKeyDown={(e) => {
          if (e.key !== "Enter") return;
          // Enter resolves an unresolved link and downloads a resolved one, so
          // paste-and-hold-Enter is the whole flow.
          if (metadata) void download();
          else void resolve();
        }}
        trailing={
          <Button
            variant={metadata ? "secondary" : "primary"}
            size="sm"
            busy={resolving}
            disabled={!url.trim() || disabled}
            icon={<Icon.Resolve className="size-3.5" strokeWidth={1.75} aria-hidden />}
            onClick={() => void resolve()}
          >
            {resolving ? "Resolving" : "Fetch"}
          </Button>
        }
      />

      {error && (
        <Banner
          title="That link did not work"
          tone="danger"
          action={
            needsFullDiskAccess(error) ? (
              <Button
                size="sm"
                variant="secondary"
                icon={<Icon.Settings className="size-3.5" strokeWidth={1.75} aria-hidden />}
                onClick={() => void api.OpenFullDiskAccessSettings()}
              >
                Open System Settings
              </Button>
            ) : undefined
          }
        >
          {explain(error).message}
          {explain(error).detail && (
            // yt-dlp's own words stay reachable but never lead: the sentence
            // above is the one that tells the user what to do.
            <Details summary="Details">
              <MonoBlock text={explain(error).detail} maxHeight="10rem" copyable />
            </Details>
          )}
        </Banner>
      )}

      {resolving && <MetadataSkeleton />}
      {metadata && !resolving && <MetadataCard metadata={metadata} />}

      <QualityPicks
        quality={metadata?.quality}
        value={options.pick as string}
        disabled={disabled}
        onChange={(pick) => {
          setOptions((o) => ({ ...o, pick }) as core.Options);
          setActivePreset(null);
        }}
      />

      <PresetBar
        presets={presets}
        activeId={activePreset}
        options={options}
        onChanged={onPresetsChanged}
        onApply={(preset) => {
          setOptions({ ...preset.options, url: "" } as core.Options);
          setActivePreset(preset.id);
        }}
      />

      <div className="flex items-center gap-xs">
        <Button
          variant="tertiary"
          size="sm"
          onClick={() => setDrawerOpen((v) => !v)}
          aria-expanded={drawerOpen}
          icon={<Icon.Advanced className="size-3.5" strokeWidth={1.75} aria-hidden />}
        >
          {drawerOpen ? "Hide advanced" : "Advanced"}
        </Button>
        <Button
          variant="tertiary"
          size="sm"
          onClick={showCommand}
          icon={<Icon.Command className="size-3.5" strokeWidth={1.75} aria-hidden />}
        >
          Show command
        </Button>
        <div className="flex-1" />
        <Button
          variant="primary"
          onClick={download}
          disabled={!canDownload}
          icon={
            queued ? (
              <Icon.Ok className="size-4" strokeWidth={1.75} aria-hidden />
            ) : (
              <Icon.Download className="size-4" strokeWidth={1.75} aria-hidden />
            )
          }
        >
          {queued ? "Added" : "Download"}
        </Button>
      </div>

      {drawerOpen && (
        <AdvancedDrawer
          options={options}
          onChange={(next) => {
            setOptions(next);
            setActivePreset(null);
          }}
          onRequestClose={() => setDrawerOpen(false)}
        />
      )}

      {command && (
        <Details summary="Generated command">
          <MonoBlock text={command} copyable />
          <p className="mt-xs text-caption text-ink-tertiary">
            Progress-reporting flags are omitted; they change the output format, not the file.
          </p>
        </Details>
      )}
    </section>
  );
}

/** cleanError strips Go's wrapping so the user sees the sentence, not a trace. */
function cleanError(e: unknown): string {
  const text = String(e).replace(/^Error:\s*/, "").trim();
  return text || "Something went wrong.";
}

/**
 * explain splits a backend failure into the sentence to lead with and the raw
 * output to keep behind a toggle.
 *
 * A classified failure arrives as "plain message: yt-dlp's own output", and
 * everything yt-dlp writes to stderr starts with ERROR or WARNING. Anything
 * that does not match is shown whole rather than guessed at.
 */
function explain(error: string): { message: string; detail: string } {
  const at = error.search(/:\s(?=ERROR[:\s]|WARNING[:\s])/);
  if (at === -1) return { message: error, detail: "" };
  // slice(0, at) drops the joining colon: the message already ends in a stop.
  return { message: error.slice(0, at).trim(), detail: error.slice(at + 2).trim() };
}

/**
 * needsFullDiskAccess spots the one failure with a remedy Lasso can open
 * directly. It keys on the phrase core/errors.go puts in that message, which a
 * Go test pins.
 */
function needsFullDiskAccess(error: string): boolean {
  return error.includes("Full Disk Access");
}
