// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {binaries} from '../models';
import {core} from '../models';
import {main} from '../models';
import {presets} from '../models';

export function BinaryStatus():Promise<binaries.Status>;

export function Cancel(arg1:string):Promise<void>;

export function ChooseFolder():Promise<string>;

export function DeletePreset(arg1:string):Promise<void>;

export function Enqueue(arg1:core.Options,arg2:string):Promise<core.Item>;

export function Events():Promise<main.EventNames>;

export function FetchMetadata(arg1:string):Promise<core.Metadata>;

export function Presets():Promise<Array<presets.Preset>>;

export function QueueItems():Promise<Array<core.Item>>;

export function RenamePreset(arg1:string,arg2:string):Promise<void>;

export function Retry(arg1:string):Promise<void>;

export function RevealInFinder(arg1:string):Promise<void>;

export function SavePreset(arg1:string,arg2:core.Options):Promise<presets.Preset>;

export function SaveSettings(arg1:main.Settings):Promise<main.Settings>;

export function Settings():Promise<main.Settings>;

export function ShowCommand(arg1:core.Options):Promise<string>;

export function Thumbnail(arg1:string,arg2:number):Promise<string>;

export function UpdatePreset(arg1:string,arg2:core.Options):Promise<void>;

export function UpdateYtDlp():Promise<binaries.UpdateResult>;

export function Versions():Promise<Record<binaries.Name, string>>;
