// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {binaries} from '../models';
import {updater} from '../models';
import {main} from '../models';
import {doctor} from '../models';
import {core} from '../models';
import {history} from '../models';
import {presets} from '../models';

export function AppVersion():Promise<string>;

export function ApplyFix(arg1:string):Promise<string>;

export function BinaryStatus():Promise<binaries.Status>;

export function Cancel(arg1:string):Promise<void>;

export function CheckForUpdate(arg1:boolean):Promise<updater.Update>;

export function ChooseFolder():Promise<string>;

export function ClearFinished():Promise<number>;

export function ClearHistory():Promise<void>;

export function Commands():Promise<main.MenuCommands>;

export function DeletePreset(arg1:string):Promise<void>;

export function Diagnose():Promise<doctor.Report>;

export function DownloadAgain(arg1:string):Promise<core.Item>;

export function Enqueue(arg1:core.Options,arg2:core.Source):Promise<core.Item>;

export function EnqueuePlaylist(arg1:core.Options,arg2:string,arg3:Array<core.Entry>):Promise<number>;

export function Events():Promise<main.EventNames>;

export function FetchMetadata(arg1:string):Promise<core.Metadata>;

export function ForgetHistoryEntry(arg1:string):Promise<void>;

export function History():Promise<Array<history.Entry>>;

export function InstallUpdate():Promise<updater.Result>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFullDiskAccessSettings():Promise<void>;

export function Pause(arg1:string):Promise<void>;

export function Presets():Promise<Array<presets.Preset>>;

export function QueueItems():Promise<Array<core.Item>>;

export function RemoveFromQueue(arg1:string):Promise<void>;

export function RenamePreset(arg1:string,arg2:string):Promise<void>;

export function RestartToFinish():Promise<void>;

export function Resume(arg1:string):Promise<void>;

export function Retry(arg1:string):Promise<void>;

export function RevealInFinder(arg1:string):Promise<void>;

export function SavePreset(arg1:string,arg2:core.Options):Promise<presets.Preset>;

export function SaveSettings(arg1:main.Settings):Promise<main.Settings>;

export function Settings():Promise<main.Settings>;

export function ShouldSuggestDoctor(arg1:core.ErrorKind):Promise<boolean>;

export function ShowCommand(arg1:core.Options):Promise<string>;

export function TakeIncomingLink():Promise<string>;

export function Thumbnail(arg1:string,arg2:number):Promise<string>;

export function UpdatePreset(arg1:string,arg2:core.Options):Promise<void>;

export function UpdateYtDlp():Promise<binaries.UpdateResult>;

export function Versions():Promise<Record<binaries.Name, string>>;
