// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function ApplyFix(arg1) {
  return window['go']['main']['App']['ApplyFix'](arg1);
}

export function BinaryStatus() {
  return window['go']['main']['App']['BinaryStatus']();
}

export function Cancel(arg1) {
  return window['go']['main']['App']['Cancel'](arg1);
}

export function CheckForUpdate(arg1) {
  return window['go']['main']['App']['CheckForUpdate'](arg1);
}

export function ChooseFolder() {
  return window['go']['main']['App']['ChooseFolder']();
}

export function ClearFinished() {
  return window['go']['main']['App']['ClearFinished']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function DeletePreset(arg1) {
  return window['go']['main']['App']['DeletePreset'](arg1);
}

export function Diagnose() {
  return window['go']['main']['App']['Diagnose']();
}

export function DownloadAgain(arg1) {
  return window['go']['main']['App']['DownloadAgain'](arg1);
}

export function Enqueue(arg1, arg2) {
  return window['go']['main']['App']['Enqueue'](arg1, arg2);
}

export function EnqueuePlaylist(arg1, arg2, arg3) {
  return window['go']['main']['App']['EnqueuePlaylist'](arg1, arg2, arg3);
}

export function Events() {
  return window['go']['main']['App']['Events']();
}

export function FetchMetadata(arg1) {
  return window['go']['main']['App']['FetchMetadata'](arg1);
}

export function ForgetHistoryEntry(arg1) {
  return window['go']['main']['App']['ForgetHistoryEntry'](arg1);
}

export function History() {
  return window['go']['main']['App']['History']();
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFullDiskAccessSettings() {
  return window['go']['main']['App']['OpenFullDiskAccessSettings']();
}

export function Pause(arg1) {
  return window['go']['main']['App']['Pause'](arg1);
}

export function Presets() {
  return window['go']['main']['App']['Presets']();
}

export function QueueItems() {
  return window['go']['main']['App']['QueueItems']();
}

export function RemoveFromQueue(arg1) {
  return window['go']['main']['App']['RemoveFromQueue'](arg1);
}

export function RenamePreset(arg1, arg2) {
  return window['go']['main']['App']['RenamePreset'](arg1, arg2);
}

export function RestartToFinish() {
  return window['go']['main']['App']['RestartToFinish']();
}

export function Resume(arg1) {
  return window['go']['main']['App']['Resume'](arg1);
}

export function Retry(arg1) {
  return window['go']['main']['App']['Retry'](arg1);
}

export function RevealInFinder(arg1) {
  return window['go']['main']['App']['RevealInFinder'](arg1);
}

export function SavePreset(arg1, arg2) {
  return window['go']['main']['App']['SavePreset'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Settings() {
  return window['go']['main']['App']['Settings']();
}

export function ShouldSuggestDoctor(arg1) {
  return window['go']['main']['App']['ShouldSuggestDoctor'](arg1);
}

export function ShowCommand(arg1) {
  return window['go']['main']['App']['ShowCommand'](arg1);
}

export function Thumbnail(arg1, arg2) {
  return window['go']['main']['App']['Thumbnail'](arg1, arg2);
}

export function UpdatePreset(arg1, arg2) {
  return window['go']['main']['App']['UpdatePreset'](arg1, arg2);
}

export function UpdateYtDlp() {
  return window['go']['main']['App']['UpdateYtDlp']();
}

export function Versions() {
  return window['go']['main']['App']['Versions']();
}
