package core

import (
	"fmt"
	"net/url"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

// QuickPick is the one-click quality choice on the main screen.
type QuickPick string

// A resolution pick is a rung of tierLadder followed by "p", so every rung the
// quality list can offer is a pick the arg builder can cap at. These name the
// common ones; maxHeight reads any rung.
const (
	PickBest  QuickPick = "best"
	Pick4320p QuickPick = "4320p"
	Pick2160p QuickPick = "2160p"
	Pick1440p QuickPick = "1440p"
	Pick1080p QuickPick = "1080p"
	Pick720p  QuickPick = "720p"
	Pick480p  QuickPick = "480p"
	Pick360p  QuickPick = "360p"
	// PickAudioOriginal keeps the site's own audio stream, changing only the
	// container it sits in. It is the highest-quality audio any site can give
	// you: every other audio pick re-encodes, and re-encoding a lossy stream
	// loses a second time.
	PickAudioOriginal QuickPick = "audio-original"
	PickAudioMP3      QuickPick = "audio-mp3"
	PickAudioM4A      QuickPick = "audio-m4a"
	PickAudioFLAC     QuickPick = "audio-flac"
	PickAudioOpus     QuickPick = "audio-opus"
)

// maxHeight is the vertical resolution cap a pick implies, or 0 for no cap.
func (p QuickPick) maxHeight() int {
	digits, ok := strings.CutSuffix(string(p), "p")
	if !ok {
		return 0
	}
	height, err := strconv.Atoi(digits)
	if err != nil {
		return 0
	}
	// Read off the ladder rather than a list of its own: the two used to be
	// separate, and 8K, 480p and 360p were offered but downloaded as Best.
	for _, rung := range tierLadder {
		if rung.height == height {
			return height
		}
	}
	return 0
}

// Known reports whether the pick is one Lasso offers. An unknown one is
// refused rather than downloaded as Best, which is what it used to become.
func (p QuickPick) Known() bool {
	return p == "" || p == PickBest || p.IsAudioOnly() || p.maxHeight() > 0
}

// audioFormat is the target format for an audio-only pick, or "" for video.
//
// "best" is yt-dlp's word for "do not re-encode": it extracts the stream and
// leaves the codec alone.
func (p QuickPick) audioFormat() string {
	switch p {
	case PickAudioOriginal:
		return "best"
	case PickAudioMP3:
		return "mp3"
	case PickAudioM4A:
		return "m4a"
	case PickAudioFLAC:
		return "flac"
	case PickAudioOpus:
		return "opus"
	default:
		return ""
	}
}

// IsAudioOnly reports whether the pick produces an audio file.
func (p QuickPick) IsAudioOnly() bool { return p.audioFormat() != "" }

// Container is the output container for video downloads.
type Container string

const (
	ContainerAuto Container = ""
	ContainerMP4  Container = "mp4"
	ContainerMKV  Container = "mkv"
	ContainerWebM Container = "webm"
)

// VideoCodec is a preferred video codec. Preferences are soft: yt-dlp falls
// back to whatever is available rather than failing.
type VideoCodec string

const (
	VideoCodecAuto VideoCodec = ""
	VideoCodecH264 VideoCodec = "h264"
	VideoCodecH265 VideoCodec = "h265"
	VideoCodecVP9  VideoCodec = "vp9"
	VideoCodecAV1  VideoCodec = "av01"
)

// AudioCodec is a preferred audio codec for the audio track of a video.
type AudioCodec string

const (
	AudioCodecAuto AudioCodec = ""
	AudioCodecAAC  AudioCodec = "aac"
	AudioCodecOpus AudioCodec = "opus"
	AudioCodecMP3  AudioCodec = "mp3"
)

// SponsorBlockMode says what to do with SponsorBlock segments.
type SponsorBlockMode string

const (
	SponsorBlockOff    SponsorBlockMode = ""
	SponsorBlockRemove SponsorBlockMode = "remove"
	SponsorBlockMark   SponsorBlockMode = "mark"
)

// DefaultSponsorBlockCategories is what "SponsorBlock on" means when the user
// has not narrowed it down.
var DefaultSponsorBlockCategories = []string{"sponsor"}

// Browser is a source of cookies.
type Browser string

const (
	BrowserNone    Browser = ""
	BrowserSafari  Browser = "safari"
	BrowserChrome  Browser = "chrome"
	BrowserFirefox Browser = "firefox"
	BrowserBrave   Browser = "brave"
	BrowserArc     Browser = "arc"
)

// Name is the browser as a person would write it.
func (b Browser) Name() string {
	switch b {
	case BrowserSafari:
		return "Safari"
	case BrowserChrome:
		return "Chrome"
	case BrowserFirefox:
		return "Firefox"
	case BrowserBrave:
		return "Brave"
	case BrowserArc:
		return "Arc"
	}
	return string(b)
}

// Subtitles groups the subtitle options.
type Subtitles struct {
	Download      bool     `json:"download"`
	Embed         bool     `json:"embed"`
	Languages     []string `json:"languages"`
	AutoGenerated bool     `json:"autoGenerated"`
}

// Enhancements groups the post-processing options.
type Enhancements struct {
	SponsorBlock           SponsorBlockMode `json:"sponsorBlock"`
	SponsorBlockCategories []string         `json:"sponsorBlockCategories"`
	EmbedChapters          bool             `json:"embedChapters"`
	EmbedThumbnail         bool             `json:"embedThumbnail"`
	EmbedMetadata          bool             `json:"embedMetadata"`
}

// Music groups the options that only make sense when the download is music.
type Music struct {
	// Tags fills in artist, title and year from the fields the site provides,
	// falling back to splitting an "Artist - Title" video title.
	Tags bool `json:"tags"`
	// SplitChapters writes one file per chapter, which is how a single
	// hour-long "full album" upload becomes an album. The whole recording is
	// kept alongside the tracks: yt-dlp does not remove it, and deleting a
	// file the user did not ask to lose is not Lasso's call.
	SplitChapters bool `json:"splitChapters"`
}

// WantsMusic reports whether either music option is on.
func (m Music) WantsMusic() bool { return m.Tags || m.SplitChapters }

// Playlist narrows which items of a playlist are downloaded. Start and End are
// 1-based and inclusive; zero means unbounded on that side.
type Playlist struct {
	Start   int  `json:"start"`
	End     int  `json:"end"`
	Reverse bool `json:"reverse"`
}

// Network groups transfer and authentication options.
type Network struct {
	// RateLimit is a yt-dlp rate string such as "2M" or "500K". Empty is
	// unlimited.
	RateLimit string  `json:"rateLimit"`
	Cookies   Browser `json:"cookies"`
}

// Output controls where files land and what they are called.
type Output struct {
	Folder   string `json:"folder"`
	Template string `json:"template"`
}

// DefaultTemplate is the filename template used when none is set.
const DefaultTemplate = "%(title)s [%(id)s].%(ext)s"

// defaultTemplate is DefaultTemplate for a pick.
//
// A resolution pick carries its rung in the name, "Title [id] 480p.mp4".
// yt-dlp skips a download whose file already exists, and without the rung a
// 480p copy of something already saved in 4K had the same name — so it
// finished at once, pointing at the 4K file. The label is Lasso's own rather
// than yt-dlp's height field, which is the long side of a vertical video.
//
// A converted audio pick carries its format the same way: "Title [id] MP3.mp3".
// Every audio pick fetches the same highest-bitrate stream first (-S abr), so
// without it an MP3's source file had the very name of an Original saved
// earlier — "Title [id].m4a" — and yt-dlp, finding it, converted it and then
// deleted it as its own intermediate. Downloading an MP3 destroyed the
// Original. Only Original keeps the plain name.
func (p QuickPick) defaultTemplate() string {
	if height := p.maxHeight(); height > 0 {
		return "%(title)s [%(id)s] " + ResolutionLabel(height) + ".%(ext)s"
	}
	if format := p.audioFormat(); format != "" && format != "best" {
		return "%(title)s [%(id)s] " + strings.ToUpper(format) + ".%(ext)s"
	}
	return DefaultTemplate
}

// defaultTemplate is DefaultTemplate for these options: the pick's, and the
// clip's times when there is one, so a clip never shares a name with the
// whole video or with a different clip.
func (o Options) defaultTemplate() string {
	template := o.Pick.defaultTemplate()
	if o.Clip.IsWhole() {
		return template
	}
	return strings.TrimSuffix(template, ".%(ext)s") + " " + o.Clip.fileLabel() + ".%(ext)s"
}

// Options is the complete description of one download request. It is the sole
// input to BuildArgs, which is a pure function of it.
type Options struct {
	URL        string     `json:"url"`
	Pick       QuickPick  `json:"pick"`
	Container  Container  `json:"container"`
	VideoCodec VideoCodec `json:"videoCodec"`
	AudioCodec AudioCodec `json:"audioCodec"`
	// PreferHDR asks for the high-dynamic-range encode where one exists. It is
	// a preference, not a filter: a video with no HDR encode still downloads.
	PreferHDR    bool         `json:"preferHDR"`
	Subtitles    Subtitles    `json:"subtitles"`
	Enhancements Enhancements `json:"enhancements"`
	Playlist     Playlist     `json:"playlist"`
	Music        Music        `json:"music"`
	// Clip is part of the video to download instead of all of it.
	Clip    Clip    `json:"clip"`
	Network Network `json:"network"`
	Output  Output  `json:"output"`

	// FFmpegLocation is the directory holding the bundled ffmpeg and ffprobe.
	// It lives here so BuildArgs stays a pure function and so the command shown
	// to the user is the command that actually runs.
	FFmpegLocation string `json:"ffmpegLocation"`

	// ArcProfileDir is where Arc keeps its Chromium profile. yt-dlp has no
	// "arc" browser, so Arc is requested as Chromium with an explicit profile.
	ArcProfileDir string `json:"arcProfileDir"`

	// Playback is what this Mac plays natively, which decides the codec and
	// container "Best" prefers. The backend fills it in; see Playback.
	Playback Playback `json:"playback"`

	// DenoPath is the bundled deno, which yt-dlp needs as a JavaScript runtime
	// for YouTube's challenges. Lasso puts it on the subprocess PATH, but the
	// command shown to the user has to say where it is explicitly or a paste
	// into a terminal silently loses formats.
	DenoPath string `json:"denoPath"`
}

var rateLimitPattern = regexp.MustCompile(`^[0-9]+(\.[0-9]+)?[KMG]?$`)

// Validate rejects options that are malformed or unsafe.
//
// URLs and filename templates arrive from the user and are never interpolated
// into a shell, but a template can still try to walk out of the download folder,
// and a non-http scheme is never something we want to hand to yt-dlp.
func (o Options) Validate() error {
	if strings.TrimSpace(o.URL) == "" {
		return fmt.Errorf("no URL given")
	}
	parsed, err := url.Parse(strings.TrimSpace(o.URL))
	if err != nil {
		return fmt.Errorf("that does not look like a link")
	}
	if parsed.Scheme != "http" && parsed.Scheme != "https" {
		return fmt.Errorf("only http and https links are supported")
	}
	if parsed.Host == "" {
		return fmt.Errorf("that link is missing a website address")
	}

	if o.Output.Template != "" {
		if filepath.IsAbs(o.Output.Template) {
			return fmt.Errorf("the filename template cannot be an absolute path")
		}
		for _, part := range strings.Split(filepath.ToSlash(o.Output.Template), "/") {
			if part == ".." {
				return fmt.Errorf("the filename template cannot contain ..")
			}
		}
	}

	if !o.Pick.Known() {
		return fmt.Errorf("%q is not a quality Lasso offers", string(o.Pick))
	}

	if o.Network.RateLimit != "" && !rateLimitPattern.MatchString(o.Network.RateLimit) {
		return fmt.Errorf("the speed limit should look like 500K or 2M")
	}

	if o.Playlist.Start < 0 || o.Playlist.End < 0 {
		return fmt.Errorf("playlist numbers cannot be negative")
	}
	if o.Playlist.Start > 0 && o.Playlist.End > 0 && o.Playlist.End < o.Playlist.Start {
		return fmt.Errorf("the playlist range ends before it starts")
	}

	if o.Network.Cookies == BrowserArc && o.ArcProfileDir == "" {
		return fmt.Errorf("Arc's profile folder could not be found")
	}
	return nil
}

// WantsSubtitles reports whether the request asks for subtitles at all.
func (o Options) WantsSubtitles() bool {
	return o.Subtitles.Download || o.Subtitles.Embed || o.Subtitles.AutoGenerated
}

// WithoutSubtitles returns a copy with every subtitle option cleared.
//
// yt-dlp treats a failed subtitle fetch as fatal and has no flag to ignore
// only that (--ignore-errors would also swallow a genuinely broken video), so
// salvaging the download means asking again without them.
func (o Options) WithoutSubtitles() Options {
	o.Subtitles = Subtitles{}
	return o
}
