import { useEffect, useMemo, useRef, useState } from "react";
import type { ReactNode } from "react";
import {
  Banner,
  Button,
  Chip,
  Details,
  Dropdown,
  Eyebrow,
  Icon,
  Input,
  MonoBlock,
  Sheet,
  Skeleton,
  Tag,
  VirtualList,
  cx,
} from "@lasso/ui";
import { api, core, presets as presetModels } from "../bindings";
import { formatBytes, formatDuration, formatLength, isWhole, kindOf, parseTime, shortLink, siteOf } from "../format";
import type { Clip, Kind } from "../format";
import { AdvancedDrawer } from "../components/AdvancedDrawer";
import { MediaThumb, bestSource } from "../components/MediaThumb";
import type { Link } from "../hooks/useLink";
import { cleanError, explain, needsFullDiskAccess } from "../hooks/useLink";
import { useDoctor, useSuggestsDoctor } from "../components/DoctorPanel";

const EMPTY_OPTIONS = {
  url: "",
  pick: "best",
  container: "",
  videoCodec: "",
  audioCodec: "",
  subtitles: { download: false, embed: false, languages: [], autoGenerated: false },
  enhancements: { sponsorBlock: "", sponsorBlockCategories: [], embedChapters: false, embedThumbnail: false, embedMetadata: false },
  playlist: { start: 0, end: 0, reverse: false },
  network: { rateLimit: "", cookies: "" },
  output: { folder: "", template: "" },
} as unknown as core.Options;

const WHOLE: Clip = { start: 0, end: 0 };

/** clipFraction is how much of the video a clip is, 1 for all of it. */
function clipFraction(clip: Clip, duration: number): number {
  if (isWhole(clip) || duration <= 0) return 1;
  const end = clip.end > 0 ? Math.min(clip.end, duration) : duration;
  return Math.min(1, Math.max(0, (end - clip.start) / duration));
}

/**
 * ClipSection takes part of the video instead of all of it. Whole is the
 * default and asks for nothing; a part asks for two times, in the forms people
 * type them. The download cuts exactly there, re-encoding around each edge,
 * which is why it takes a little longer than its size suggests.
 */
function ClipSection({
  duration,
  clip,
  problem,
  onChange,
}: {
  duration: number;
  clip: Clip;
  problem: string;
  /** The clip to download, and why its times cannot be cut ("" when they can). */
  onChange: (clip: Clip, problem: string) => void;
}) {
  const [part, setPart] = useState(!isWhole(clip));
  const [from, setFrom] = useState(clip.start > 0 ? formatDuration(clip.start) : "0:00");
  const [to, setTo] = useState(formatDuration(clip.end > 0 ? clip.end : duration));

  function cut(nextFrom: string, nextTo: string) {
    setFrom(nextFrom);
    setTo(nextTo);
    const start = parseTime(nextFrom);
    const end = parseTime(nextTo);
    if (Number.isNaN(start) || Number.isNaN(end)) {
      onChange(clip, "Times look like 1:30 or 1:02:03.");
    } else if (end <= start) {
      onChange(clip, "The clip ends before it starts.");
    } else if (start >= duration || end > Math.ceil(duration)) {
      onChange(clip, `The video is ${formatDuration(duration)} long.`);
    } else {
      // Running to the last second is the same as to the end, which yt-dlp
      // cuts more simply.
      onChange({ start, end: end >= Math.floor(duration) ? 0 : end }, "");
    }
  }

  const start = parseTime(from);
  const end = parseTime(to);
  const length = !problem && end > start ? end - start : 0;

  return (
    <section className="flex flex-col gap-xs">
      <Eyebrow>Length</Eyebrow>
      <div className="flex flex-wrap items-center gap-sm">
        <div className="flex gap-xxs">
          <Chip
            selected={!part}
            onClick={() => {
              setPart(false);
              onChange(WHOLE, "");
            }}
          >
            All of it · {formatDuration(duration)}
          </Chip>
          <Chip
            selected={part}
            onClick={() => {
              setPart(true);
              cut(from, to);
            }}
          >
            Just a part
          </Chip>
        </div>
        {part && (
          <div className="flex items-center gap-xs text-body-sm text-ink-muted">
            <span>From</span>
            <Input
              className="w-24"
              value={from}
              invalid={Boolean(problem) && Number.isNaN(start)}
              aria-label="Clip starts at"
              onChange={(e) => cut(e.target.value, to)}
            />
            <span>to</span>
            <Input
              className="w-24"
              value={to}
              invalid={Boolean(problem) && !Number.isNaN(start)}
              aria-label="Clip ends at"
              onChange={(e) => cut(from, e.target.value)}
            />
            {length > 0 && <span className="text-ink-subtle">{formatDuration(length)} long</span>}
          </div>
        )}
      </div>
      {part && (
        <p className={cx("text-body-sm", problem ? "text-danger-strong" : "text-ink-subtle")} role={problem ? "alert" : undefined}>
          {problem || "Cut at exactly these times. It takes a little longer, because the edges are re-encoded."}
        </p>
      )}
    </section>
  );
}

/** One row of the quality list. */
type Choice = {
  pick: string;
  label: string;
  detail?: string;
  note?: string;
  hint?: string;
  tags?: ReactNode;
  bytes: number;
  estimate?: boolean;
};

/**
 * ChooseScreen is a resolved link and the one decision it needs: what to keep.
 *
 * Video or audio first, as two large cards in their category colours, then one
 * list of qualities with what each will cost. Everything else yt-dlp can do is
 * one button away in More options, and the button that starts the download
 * says what it will produce.
 */
export function ChooseScreen({
  link,
  presets,
  onPresetsChanged,
  disabled,
  onQueued,
  downloadRequests,
}: {
  link: Link;
  presets: presetModels.Preset[] | null;
  onPresetsChanged: () => void;
  disabled: boolean;
  onQueued: () => void;
  /** Counts File › Download presses; a change is a request to download. */
  downloadRequests: number;
}) {
  const { metadata, resolving, error } = link;
  const [options, setOptions] = useState<core.Options>(EMPTY_OPTIONS);
  const [activePreset, setActivePreset] = useState("");
  const [moreOpen, setMoreOpen] = useState(false);
  const [busy, setBusy] = useState(false);
  const [queueError, setQueueError] = useState("");
  const [selected, setSelected] = useState<Set<number>>(new Set());
  // Why the clip's times cannot be cut, or "" when they can (or there is none).
  const [clipProblem, setClipProblem] = useState("");

  const quality = metadata?.quality;
  const playlist = metadata?.kind === "playlist";
  const entries = metadata?.entries ?? [];
  const kind = kindOf(options.pick as string);

  // A new link keeps the choice made for the last one when it can be honoured
  // — someone saving an album's worth of songs one link at a time should not
  // have to pick Audio every time — and falls back to the default when not.
  useEffect(() => {
    if (!metadata) return;
    setQueueError("");
    setSelected(new Set(entries.map((_, i) => i)));
    // A clip's times belong to the video they were chosen on.
    setOptions((o) => ({ ...o, pick: validPick(o.pick as string, metadata.quality), clip: WHOLE }) as core.Options);
    setClipProblem("");
    // Only a new link resets the choice; editing options must not.
  }, [metadata]);

  // Escape backs out of the link. The screen takes focus when it opens so that
  // works straight after a paste, and the handler is on the screen rather than
  // the window so Escape in Settings or Diagnostics never reaches it. More
  // options is a portal inside this tree, so its Escape is excluded by hand.
  const root = useRef<HTMLDivElement>(null);
  useEffect(() => {
    if (!root.current?.contains(document.activeElement)) root.current?.focus();
  }, []);

  function choose(pick: string) {
    setOptions((o) => ({ ...o, pick }) as core.Options);
    setActivePreset("");
    setQueueError("");
  }

  function chooseKind(next: Kind) {
    if (next === kind) return;
    choose(next === "audio" ? "audio-original" : "best");
  }

  async function download() {
    if (!metadata || disabled) return;
    setBusy(true);
    setQueueError("");
    try {
      const request = { ...options, url: link.url } as core.Options;
      if (playlist) {
        const chosen = entries.filter((_, i) => selected.has(i));
        // The ticked videos are the selection; a range carried in by a saved
        // choice would narrow it again without saying so.
        const whole = { ...request, playlist: { start: 0, end: 0, reverse: false } } as core.Options;
        await api.EnqueuePlaylist(whole, metadata.title, chosen);
      } else {
        await api.Enqueue(request, {
          title: metadata.title,
          uploader: metadata.uploader,
          // A clip's file is the clip's length, which is what its thumbnail
          // says in the queue and in History.
          duration: Math.round(metadata.duration * clipFraction(options.clip ?? WHOLE, metadata.duration)),
          thumbnail: bestSource(metadata.thumbnails, 320),
        });
      }
      onQueued();
    } catch (e) {
      setQueueError(cleanError(e));
    } finally {
      setBusy(false);
    }
  }

  const clip: Clip = options.clip ?? WHOLE;
  const fraction = playlist ? 1 : clipFraction(clip, metadata?.duration ?? 0);
  const choices = useMemo(() => {
    const all = kind === "audio" ? audioChoices(quality) : videoChoices(quality);
    // A clip costs its share of the whole, roughly: the edges are re-encoded.
    return fraction < 1 ? all.map((c) => ({ ...c, bytes: Math.round(c.bytes * fraction), estimate: true })) : all;
  }, [kind, quality, fraction]);
  const current = choices.find((c) => c.pick === options.pick);
  const count = playlist ? selected.size : 1;
  const canDownload =
    Boolean(metadata) && !metadata?.blocked && !resolving && !disabled && !busy && count > 0 && !clipProblem;

  // ⌘↩. Only presses made while this screen is open count: the counter's
  // value on arrival is where it starts.
  const seenRequests = useRef(downloadRequests);
  useEffect(() => {
    if (downloadRequests === seenRequests.current) return;
    seenRequests.current = downloadRequests;
    if (canDownload && !moreOpen) void download();
    // download reads the latest state itself; only a new press should run it.
  }, [downloadRequests]);

  return (
    <div
      ref={root}
      tabIndex={-1}
      className="flex min-h-0 flex-1 flex-col outline-none"
      onKeyDown={(e) => {
        if (e.key === "Escape" && !moreOpen) link.clear();
      }}
    >
      <div className="min-h-0 flex-1 overflow-y-auto">
        <div className="mx-auto flex w-full max-w-page flex-col gap-lg px-xl pt-md pb-lg">
          <LinkBar url={link.url} onClear={link.clear} />

          {error ? (
            <ResolveError error={error} kind={link.errorKind} onRetry={() => void link.resolve(link.url)} />
          ) : resolving || !metadata ? (
            <ChooseSkeleton />
          ) : (
            <>
              <Header metadata={metadata} url={link.url} />

              {metadata.blocked ? (
                <Banner title="Not yet" tone="neutral">
                  {metadata.blocked}
                </Banner>
              ) : (
                <>
                  <section className="flex flex-col gap-xs">
                    <div className="flex items-center justify-between gap-sm">
                      <Eyebrow>Save as</Eyebrow>
                      <SavedChoices
                        presets={presets}
                        active={activePreset}
                        options={options}
                        onChanged={onPresetsChanged}
                        onApply={(preset) => {
                          setOptions({
                            ...preset.options,
                            url: "",
                            pick: validPick(preset.options.pick as string, quality),
                            // Saved choices say how to download, not what: the clip stays.
                            clip: options.clip ?? WHOLE,
                          } as core.Options);
                          setActivePreset(preset.id);
                        }}
                      />
                    </div>
                    <KindTiles quality={quality} kind={kind} onChoose={chooseKind} />
                  </section>

                  {quality?.limited && kind === "video" && (
                    <Banner title="Only a low quality was offered" tone="neutral">
                      Sites hold their higher qualities back from visitors who are not signed in.
                      Turn on cookies from your browser in Settings, then paste the link again.
                    </Banner>
                  )}

                  <section className="flex flex-col gap-xs">
                    <Eyebrow>{kind === "audio" ? "Format" : playlist ? "Quality, for each video" : "Quality"}</Eyebrow>
                    <QualityList choices={choices} value={options.pick as string} onChange={choose} />
                    <p className="text-body-sm text-ink-subtle">{footnote(kind, options, quality, current)}</p>
                  </section>

                  {!playlist && metadata.duration > 0 && (
                    <ClipSection
                      key={link.url}
                      duration={metadata.duration}
                      clip={clip}
                      problem={clipProblem}
                      onChange={(next, problem) => {
                        setOptions((o) => ({ ...o, clip: next }) as core.Options);
                        setClipProblem(problem);
                        setQueueError("");
                      }}
                    />
                  )}

                  {playlist && <PlaylistPicker entries={entries} selected={selected} onChange={setSelected} />}
                </>
              )}
            </>
          )}
        </div>
      </div>

      <footer className="shrink-0 border-t border-hairline bg-canvas">
        <div className="mx-auto flex w-full max-w-page items-center gap-sm px-xl py-sm">
          <Button
            variant="tertiary"
            onClick={() => setMoreOpen(true)}
            disabled={!metadata}
            icon={<Icon.Advanced className="size-3.5" strokeWidth={1.75} aria-hidden />}
          >
            More options
          </Button>
          <span className="hidden truncate text-body-sm text-ink-subtle lg:inline">
            Subtitles, chapters, SponsorBlock, file names
          </span>
          <div className="flex-1" />
          {queueError && (
            <span className="max-w-note text-body-sm text-danger-strong" role="alert">
              {queueError}
            </span>
          )}
          <Button
            variant="primary"
            size="lg"
            busy={busy}
            disabled={!canDownload}
            onClick={() => void download()}
            icon={<Icon.Download className="size-4" strokeWidth={1.75} aria-hidden />}
          >
            {downloadLabel(playlist, count, current)}
          </Button>
        </div>
      </footer>

      <MoreOptions
        open={moreOpen}
        onOpenChange={setMoreOpen}
        options={options}
        url={link.url}
        onChange={(next) => {
          setOptions(next);
          setActivePreset("");
        }}
      />
    </div>
  );
}

/** The link being looked at, with the way back out. */
function LinkBar({ url, onClear }: { url: string; onClear: () => void }) {
  return (
    <div className="flex h-11 items-center gap-xs rounded-sm border border-hairline bg-canvas pr-xxs pl-sm">
      <Icon.LinkIcon className="size-4 shrink-0 text-ink-subtle" strokeWidth={1.75} aria-hidden />
      <span className="min-w-0 flex-1 truncate text-body-sm text-ink-muted" title={url} data-selectable>
        {shortLink(url)}
      </span>
      <Button size="icon" variant="tertiary" aria-label="Clear link" title="Clear link (Esc)" onClick={onClear}>
        <Icon.Cancel className="size-4" strokeWidth={1.75} aria-hidden />
      </Button>
    </div>
  );
}

/** What the link turned out to be. */
function Header({ metadata, url }: { metadata: core.Metadata; url: string }) {
  const playlist = metadata.kind === "playlist";
  const count = metadata.entries?.length ?? 0;
  const meta = playlist
    ? ["Playlist", count === 1 ? "1 video" : `${count} videos`, metadata.uploader]
    : [metadata.uploader, formatLength(metadata.duration), siteOf(metadata.webpageUrl || url)];

  return (
    <div className="flex items-center gap-lg">
      <MediaThumb
        source={bestSource(metadata.thumbnails, 320)}
        duration={playlist ? 0 : metadata.duration}
        size="large"
      />
      <div className="flex min-w-0 flex-col gap-xxs">
        <h1 className="line-clamp-2 text-heading text-ink" title={metadata.title} data-selectable>
          {metadata.title || shortLink(url)}
        </h1>
        <span className="truncate text-body-sm text-ink-subtle">{meta.filter(Boolean).join(" · ")}</span>
      </div>
    </div>
  );
}

/**
 * KindTiles are the first decision, drawn as the system's category cards.
 *
 * A chosen card fills with its colour — purple for video, green for audio —
 * which is the one place in the app the accents are used at full size. They
 * are surfaces, not buttons in the conversion sense: the button that acts is
 * the near-black one at the bottom.
 */
function KindTiles({
  quality,
  kind,
  onChoose,
}: {
  quality?: core.QualityOptions;
  kind: Kind;
  onChoose: (kind: Kind) => void;
}) {
  const hasVideo = quality?.hasVideo ?? true;
  const hasAudio = quality?.hasAudio ?? true;

  let videoLine = "The picture and the sound, as one file";
  if (quality?.approximate) videoLine = "Each video at the best quality this Mac plays";
  else if (quality?.bestLabel)
    videoLine = quality.bestPlayable
      ? `Up to ${quality.bestLabel}, ready to play on this Mac`
      : `Up to ${quality.bestLabel}; plays in IINA or VLC`;

  return (
    <div className="grid grid-cols-2 gap-md" role="radiogroup" aria-label="What to save">
      <Tile
        tone="video"
        selected={kind === "video"}
        disabled={!hasVideo}
        title="Video"
        line={hasVideo ? videoLine : "This link has no video"}
        onClick={() => onChoose("video")}
      />
      <Tile
        tone="audio"
        selected={kind === "audio"}
        disabled={!hasAudio}
        title="Audio only"
        line={hasAudio ? "Just the sound, as its own file" : "This link has no sound"}
        onClick={() => onChoose("audio")}
      />
    </div>
  );
}

function Tile({
  tone,
  selected,
  disabled,
  title,
  line,
  onClick,
}: {
  tone: Kind;
  selected: boolean;
  disabled: boolean;
  title: string;
  line: string;
  onClick: () => void;
}) {
  const Glyph = tone === "audio" ? Icon.Audio : Icon.Video;
  const video = tone === "video";

  return (
    <button
      type="button"
      role="radio"
      aria-checked={selected}
      disabled={disabled}
      onClick={onClick}
      className={cx(
        "no-drag flex h-21 items-center gap-md rounded-md border px-lg text-left",
        "transition-[background-color,border-color,box-shadow,color] duration-150 ease-standard",
        "disabled:cursor-not-allowed disabled:opacity-50",
        selected
          ? cx("shadow-layered", video ? "border-accent-purple bg-accent-purple text-on-fill" : "border-accent-green bg-accent-green text-on-green")
          : "border-hairline bg-canvas text-ink hover:border-hairline-strong hover:bg-surface-1",
      )}
    >
      <span
        className={cx(
          "flex size-10 shrink-0 items-center justify-center rounded-pill",
          selected
            ? video
              ? "bg-on-fill text-accent-purple"
              : "bg-on-green text-accent-green"
            : video
              ? "bg-accent-purple text-on-fill"
              : "bg-accent-green text-on-green",
        )}
      >
        <Glyph className="size-5" strokeWidth={1.75} aria-hidden />
      </span>
      <span className="flex min-w-0 flex-col gap-hair">
        <span className="text-card-title">{title}</span>
        <span className={cx("truncate text-body-sm", selected ? "" : "text-ink-subtle")}>{line}</span>
      </span>
    </button>
  );
}

/** QualityList is one list of choices, each with what it will cost. */
function QualityList({
  choices,
  value,
  onChange,
}: {
  choices: Choice[];
  value: string;
  onChange: (pick: string) => void;
}) {
  return (
    <div className="flex flex-col gap-xxs" role="radiogroup" aria-label="Quality">
      {choices.map((choice) => {
        const on = choice.pick === value;
        return (
          <button
            key={choice.pick}
            type="button"
            role="radio"
            aria-checked={on}
            onClick={() => onChange(choice.pick)}
            className={cx(
              "no-drag flex min-h-11 w-full items-center gap-sm rounded-sm border px-md py-xs text-left",
              "transition-[background-color,border-color,box-shadow] duration-150 ease-standard",
              on
                ? "border-primary bg-surface-1 ring-1 ring-primary ring-inset"
                : "border-hairline bg-canvas hover:border-hairline-strong",
            )}
          >
            <span
              className={cx(
                "flex size-4 shrink-0 items-center justify-center rounded-pill border-[1.5px]",
                on ? "border-primary" : "border-hairline-tertiary",
              )}
              aria-hidden
            >
              {on && <span className="size-2 rounded-pill bg-primary" />}
            </span>
            <span className="flex min-w-0 flex-1 flex-col">
              <span className="flex flex-wrap items-center gap-xs">
                <span className="text-subhead text-ink">{choice.label}</span>
                {choice.detail && <span className="text-body-sm text-ink-subtle">{choice.detail}</span>}
                {choice.tags}
                {choice.note && (
                  <span className="rounded-sm bg-info-surface px-1.5 py-0.5 text-caption text-info-strong">
                    {choice.note}
                  </span>
                )}
              </span>
              {choice.hint && <span className="text-body-sm text-ink-subtle">{choice.hint}</span>}
            </span>
            <span
              className="shrink-0 text-body-sm text-ink-muted tabular-nums"
              title={choice.estimate ? "An estimate, not an exact size" : undefined}
            >
              {sizeText(choice)}
            </span>
          </button>
        );
      })}
    </div>
  );
}

/**
 * SavedChoices is the old preset bar, folded into a menu: applying one is
 * occasional, so it no longer takes a row of the screen. Renaming and deleting
 * are in Settings.
 */
function SavedChoices({
  presets,
  active,
  options,
  onApply,
  onChanged,
}: {
  presets: presetModels.Preset[] | null;
  active: string;
  options: core.Options;
  onApply: (preset: presetModels.Preset) => void;
  onChanged: () => void;
}) {
  const [naming, setNaming] = useState(false);
  const [name, setName] = useState("");
  const [error, setError] = useState("");

  async function save() {
    setError("");
    try {
      await api.SavePreset(name.trim(), options);
      setName("");
      setNaming(false);
      onChanged();
    } catch (e) {
      setError(cleanError(e));
    }
  }

  if (naming) {
    return (
      <div className="flex items-center gap-xs">
        {error && <span className="text-body-sm text-danger-strong">{error}</span>}
        <Input
          autoFocus
          value={name}
          placeholder="Name these choices"
          aria-label="Name for these choices"
          className="w-52"
          onChange={(e) => setName(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === "Enter" && name.trim()) void save();
            if (e.key === "Escape") {
              e.preventDefault();
              e.stopPropagation();
              setNaming(false);
            }
          }}
        />
        <Button size="sm" variant="primary" disabled={!name.trim()} onClick={() => void save()}>
          Save
        </Button>
        <Button size="sm" variant="tertiary" onClick={() => setNaming(false)}>
          Cancel
        </Button>
      </div>
    );
  }

  return (
    <div className="flex items-center gap-xxs">
      <Dropdown
        className="w-48"
        ariaLabel="Saved choices"
        placeholder="Saved choices"
        value={active}
        options={(presets ?? []).map((p) => ({ value: p.id, label: p.name }))}
        onChange={(id) => {
          const preset = presets?.find((p) => p.id === id);
          if (preset) onApply(preset);
        }}
      />
      <Button size="sm" variant="tertiary" onClick={() => setNaming(true)}>
        Save these…
      </Button>
    </div>
  );
}

/** PLAYLIST_ROW_HEIGHT is fixed so a long playlist can be virtualised. */
const PLAYLIST_ROW_HEIGHT = 40;

/** PlaylistPicker is the list of a playlist's videos, each one to tick. */
function PlaylistPicker({
  entries,
  selected,
  onChange,
}: {
  entries: core.Entry[];
  selected: Set<number>;
  onChange: (next: Set<number>) => void;
}) {
  const indexed = useMemo(() => entries.map((entry, index) => ({ entry, index })), [entries]);
  const all = selected.size === entries.length;

  function toggle(index: number) {
    const next = new Set(selected);
    if (next.has(index)) next.delete(index);
    else next.add(index);
    onChange(next);
  }

  return (
    <section className="flex flex-col gap-xs">
      <div className="flex items-center justify-between gap-sm">
        <Eyebrow>Videos</Eyebrow>
        <div className="flex items-center gap-xs">
          <span className="text-body-sm text-ink-subtle tabular-nums">
            {selected.size} of {entries.length} chosen
          </span>
          <Button
            size="sm"
            variant="tertiary"
            onClick={() => onChange(all ? new Set() : new Set(entries.map((_, i) => i)))}
          >
            {all ? "Choose none" : "Choose all"}
          </Button>
        </div>
      </div>
      <div
        className="flex flex-col overflow-hidden rounded-md border border-hairline"
        style={{ height: Math.min(entries.length, 8) * PLAYLIST_ROW_HEIGHT + 2 }}
      >
        <VirtualList
          items={indexed}
          rowHeight={PLAYLIST_ROW_HEIGHT}
          getKey={(row) => String(row.index)}
          className="min-h-0 flex-1"
          renderRow={({ entry, index }) => (
            <label
              className="no-drag flex cursor-pointer items-center gap-sm border-b border-surface-3 px-sm hover:bg-surface-1"
              style={{ height: PLAYLIST_ROW_HEIGHT }}
            >
              <input
                type="checkbox"
                checked={selected.has(index)}
                onChange={() => toggle(index)}
                className="size-4 shrink-0 cursor-pointer accent-primary"
                aria-label={entry.title || `Video ${index + 1}`}
              />
              <span className="w-8 shrink-0 text-right text-body-sm text-ink-tertiary tabular-nums">{index + 1}</span>
              <span className="min-w-0 flex-1 truncate text-body-sm text-ink" title={entry.title}>
                {entry.title || entry.url}
              </span>
              <span className="shrink-0 text-body-sm text-ink-subtle tabular-nums">
                {formatDuration(entry.duration)}
              </span>
            </label>
          )}
        />
      </div>
    </section>
  );
}

/** MoreOptions holds everything yt-dlp can do that the screen does not show. */
function MoreOptions({
  open,
  onOpenChange,
  options,
  url,
  onChange,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  options: core.Options;
  url: string;
  onChange: (next: core.Options) => void;
}) {
  const [command, setCommand] = useState("");
  const [error, setError] = useState("");

  useEffect(() => {
    if (!open) {
      setCommand("");
      setError("");
    }
  }, [open]);

  async function showCommand() {
    setError("");
    try {
      setCommand(await api.ShowCommand({ ...options, url } as core.Options));
    } catch (e) {
      setError(cleanError(e));
    }
  }

  return (
    <Sheet
      open={open}
      onOpenChange={onOpenChange}
      title="More options"
      description="These apply to this download and are kept for the next one."
    >
      <div className="flex min-h-0 flex-col overflow-y-auto">
        <AdvancedDrawer bare options={options} onChange={onChange} onRequestClose={() => onOpenChange(false)} />
        <div className="flex flex-col gap-xs border-t border-hairline px-md py-sm">
          {command ? (
            <>
              <Eyebrow>The yt-dlp command</Eyebrow>
              <MonoBlock text={command} copyable />
              <p className="text-caption text-ink-tertiary">
                Progress-reporting flags are left out; they change what yt-dlp prints, not the file.
              </p>
            </>
          ) : (
            <div>
              <Button
                size="sm"
                variant="tertiary"
                onClick={() => void showCommand()}
                icon={<Icon.Command className="size-3.5" strokeWidth={1.75} aria-hidden />}
              >
                Show the yt-dlp command
              </Button>
            </div>
          )}
          {error && <p className="text-body-sm text-danger-strong">{error}</p>}
        </div>
      </div>
    </Sheet>
  );
}

/**
 * ResolveError is a link that did not resolve, with the way forward. When the
 * reason looks like Lasso's own setup rather than the site's answer, that
 * includes the doctor, by the same rule a failed download uses.
 */
function ResolveError({ error, kind, onRetry }: { error: string; kind: string; onRetry: () => void }) {
  const { message, detail } = explain(error);
  const suggests = useSuggestsDoctor(kind);
  const openDoctor = useDoctor();
  return (
    <Banner
      title="That link did not work"
      tone="danger"
      action={
        <div className="flex items-center gap-xs">
          {needsFullDiskAccess(error) && (
            <Button
              size="sm"
              icon={<Icon.Settings className="size-3.5" strokeWidth={1.75} aria-hidden />}
              onClick={() => void api.OpenFullDiskAccessSettings()}
            >
              Open System Settings
            </Button>
          )}
          {suggests && (
            <Button
              size="sm"
              icon={<Icon.Doctor className="size-3.5" strokeWidth={1.75} aria-hidden />}
              onClick={openDoctor}
            >
              Diagnose
            </Button>
          )}
          <Button
            size="sm"
            icon={<Icon.Retry className="size-3.5" strokeWidth={1.75} aria-hidden />}
            onClick={onRetry}
          >
            Try again
          </Button>
        </div>
      }
    >
      {message}
      {detail && (
        // yt-dlp's own words stay reachable but never lead: the sentence above
        // is the one that says what to do.
        <Details summary="Details">
          <MonoBlock text={detail} maxHeight="10rem" copyable />
        </Details>
      )}
    </Banner>
  );
}

/** ChooseSkeleton holds the screen's shape while a link resolves. */
function ChooseSkeleton() {
  return (
    <div className="flex flex-col gap-lg" aria-label="Looking up the link" aria-busy>
      <div className="flex items-center gap-lg">
        <Skeleton className="shrink-0 rounded-sm" style={{ width: 160, aspectRatio: "16 / 9" }} />
        <div className="flex min-w-0 flex-1 flex-col gap-xs">
          <Skeleton className="h-6 w-3/4" />
          <Skeleton className="h-4 w-1/3" />
        </div>
      </div>
      <div className="grid grid-cols-2 gap-md">
        <Skeleton className="h-21 rounded-md" />
        <Skeleton className="h-21 rounded-md" />
      </div>
      <div className="flex flex-col gap-xxs">
        {[0, 1, 2, 3].map((i) => (
          <Skeleton key={i} className="h-11 rounded-sm" />
        ))}
      </div>
    </div>
  );
}

// ---- The choices ----

function videoChoices(quality?: core.QualityOptions): Choice[] {
  if (!quality?.hasVideo) return [];

  const best: Choice = {
    pick: "best",
    label: "Best",
    detail: quality.approximate ? "" : quality.bestLabel,
    note: "Recommended",
    hint:
      !quality.approximate && quality.bestLabel && !quality.bestPlayable
        ? "Needs IINA or VLC: nothing this Mac plays was offered."
        : undefined,
    bytes: quality.bestBytes,
  };

  const tiers = (quality.tiers ?? [])
    // Best already stands for its own rung; listing it twice would only ask
    // which of two identical rows to pick.
    .filter((tier) => quality.approximate || tier.height !== quality.bestHeight)
    .map<Choice>((tier) => ({
      pick: `${tier.height}p`,
      label: tier.label,
      detail: tier.detail,
      tags: <TierTags tier={tier} />,
      hint: quality.approximate || tier.playable ? undefined : "Needs IINA or VLC to play on this Mac.",
      bytes: tier.bytes,
    }));

  return [best, ...tiers];
}

function audioChoices(quality?: core.QualityOptions): Choice[] {
  if (quality && !quality.hasAudio) return [];
  const size = (pick: string) => quality?.audioSizes?.[pick];

  const list: Array<Omit<Choice, "bytes" | "estimate">> = [
    { pick: "audio-original", label: "Original", note: "Recommended", hint: "The site's own audio, untouched." },
    { pick: "audio-m4a", label: "M4A", hint: "What Music and iPhone use." },
    { pick: "audio-mp3", label: "MP3", hint: "Plays anywhere. Converted, so a little is lost." },
    { pick: "audio-opus", label: "Opus", hint: "Smallest for the same sound; not every player opens it." },
    {
      pick: "audio-flac",
      label: "FLAC",
      hint: quality?.losslessAudio
        ? "Lossless, from a lossless source."
        : "Bigger, not better: this source is already compressed.",
    },
  ];
  return list.map((c) => ({ ...c, bytes: size(c.pick)?.bytes ?? 0, estimate: size(c.pick)?.estimate ?? false }));
}

function TierTags({ tier }: { tier: core.ResolutionTier }) {
  if (!tier.hasHDR && !tier.hasHighFrameRate) return null;
  return (
    <span className="flex gap-xxs">
      {tier.hasHDR && (
        <Tag tone="purple" title={`High dynamic range (${tier.hdrFormat || "HDR"})`}>
          {tier.hdrFormat || "HDR"}
        </Tag>
      )}
      {tier.hasHighFrameRate && (
        <Tag tone="blue" title="60 frames a second or more">
          60 fps
        </Tag>
      )}
    </span>
  );
}

/** validPick keeps a pick that this link can honour, and replaces one it cannot. */
function validPick(pick: string, quality?: core.QualityOptions): string {
  if (!quality) return pick || "best";
  if (pick?.startsWith("audio-")) return quality.hasAudio ? pick : "best";
  if (!quality.hasVideo) return "audio-original";
  if (!pick || pick === "best") return "best";
  return (quality.tiers ?? []).some((t) => `${t.height}p` === pick) ? pick : "best";
}

function sizeText(choice?: Choice): string {
  const text = choice ? formatBytes(choice.bytes) : "";
  if (!text) return "";
  return choice?.estimate ? `~${text}` : text;
}

function downloadLabel(playlist: boolean, count: number, current?: Choice): string {
  if (playlist) return count === 1 ? "Download 1 video" : `Download ${count} videos`;
  const size = sizeText(current);
  return size ? `Download · ${size}` : "Download";
}

/** footnote says what the chosen file will be, in terms of what opens it. */
function footnote(kind: Kind, options: core.Options, quality?: core.QualityOptions, current?: Choice): string {
  if (kind === "audio") {
    return options.pick === "audio-original"
      ? "Kept as the site sent it, usually M4A or Opus, with nothing converted."
      : "Converted by ffmpeg once the download finishes.";
  }
  if (options.container || options.videoCodec) {
    return "Saved in the format set in More options.";
  }
  if (quality?.approximate) {
    return "Each video is saved as MP4 where it can be, which QuickTime, Quick Look and Photos open.";
  }
  if (current?.hint) {
    return "That quality only comes in a format QuickTime cannot open. IINA and VLC play it; Best is the largest that plays here.";
  }
  return "Saved as MP4, which QuickTime, Quick Look, Photos and iMovie open.";
}
