// Package presets provides Lasso's built-in presets and CRUD for user presets,
// persisted as JSON under ~/Library/Application Support/Lasso.
package presets

import (
	"github.com/swayyaam/lasso/packages/core"
)

// Preset is a named set of download options.
//
// The URL is always empty: a preset describes how to download, not what. The
// caller merges it with whatever link is in the box.
type Preset struct {
	ID      string       `json:"id"`
	Name    string       `json:"name"`
	Options core.Options `json:"options"`
	// BuiltIn presets ship with Lasso and cannot be renamed or deleted.
	BuiltIn bool `json:"builtIn"`
}

// Apply returns the preset's options with a URL filled in, leaving the preset
// itself untouched.
func (p Preset) Apply(url string) core.Options {
	o := p.Options
	o.URL = url
	return o
}

// Built-in preset identifiers. They are stable so the UI can refer to one.
const (
	IDBestQuality  = "builtin-best-quality"
	IDArchiveMKV   = "builtin-archive-mkv"
	IDPodcastAudio = "builtin-podcast-audio"
	IDMusicFLAC    = "builtin-music-flac"
)

// Builtins returns the presets that ship with Lasso, in display order.
//
// A fresh slice is returned each call so a caller cannot mutate the originals.
func Builtins() []Preset {
	return []Preset{
		{
			ID:      IDBestQuality,
			Name:    "Best quality",
			BuiltIn: true,
			Options: core.Options{
				Pick: core.PickBest,
				Enhancements: core.Enhancements{
					EmbedChapters:  true,
					EmbedThumbnail: true,
					EmbedMetadata:  true,
				},
			},
		},
		{
			ID:      IDArchiveMKV,
			Name:    "Archive (MKV)",
			BuiltIn: true,
			Options: core.Options{
				Pick: core.PickBest,
				// MKV holds any codec and any number of subtitle tracks, which
				// is what makes it the right container for keeping something.
				Container: core.ContainerMKV,
				Subtitles: core.Subtitles{
					Download:      true,
					Embed:         true,
					AutoGenerated: true,
					Languages:     []string{"en"},
				},
				Enhancements: core.Enhancements{
					EmbedChapters:  true,
					EmbedThumbnail: true,
					EmbedMetadata:  true,
				},
			},
		},
		{
			ID:      IDPodcastAudio,
			Name:    "Podcast audio",
			BuiltIn: true,
			Options: core.Options{
				Pick: core.PickAudioMP3,
				Enhancements: core.Enhancements{
					EmbedChapters:  true,
					EmbedThumbnail: true,
					EmbedMetadata:  true,
					// Spoken-word content is where sponsor segments are most
					// worth removing outright.
					SponsorBlock:           core.SponsorBlockRemove,
					SponsorBlockCategories: []string{"sponsor", "selfpromo"},
				},
			},
		},
		{
			ID:      IDMusicFLAC,
			Name:    "Music (FLAC)",
			BuiltIn: true,
			Options: core.Options{
				Pick: core.PickAudioFLAC,
				Enhancements: core.Enhancements{
					EmbedThumbnail: true,
					EmbedMetadata:  true,
				},
			},
		},
	}
}

// IsBuiltinID reports whether an id belongs to a shipped preset.
func IsBuiltinID(id string) bool {
	for _, p := range Builtins() {
		if p.ID == id {
			return true
		}
	}
	return false
}
